version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /pgdata
  api:
    image: cars-graph-api
    ports: ["4000:4000"]
    environment:
      PG_LOCAL_HOST: db
    restart: on-failure