db:
  type: postgres
  host: localhost
  port: 15432
  username: postgres
  password: postgres
  database: postgres
  synchronize: false
  logging: false
  entities: [
    dist/entities/**/*entity.js
  ]